2024-12-12 06:32:44,881 INFO: User disconnecting: Hollow [in /home/runner/TornadoChatRoom/app.py:426]
2024-12-12 06:32:44,883 INFO: User disconnected: Hollow [in /home/runner/TornadoChatRoom/app.py:429]
2024-12-12 06:32:45,018 INFO: Socket connection attempt from 0pROEBm7F_5pd1p-AAAT [in /home/runner/TornadoChatRoom/app.py:378]
2024-12-12 06:32:45,282 INFO: Socket connection authenticated for user: Hollow [in /home/runner/TornadoChatRoom/app.py:384]
2024-12-12 06:32:45,282 INFO: Authenticated user connecting: Hollow [in /home/runner/TornadoChatRoom/app.py:386]
2024-12-12 06:32:45,999 INFO: Client connected successfully: Hollow [in /home/runner/TornadoChatRoom/app.py:413]
2024-12-12 06:32:46,516 INFO: Socket connection attempt from BaMSophFvVudBozaAAAV [in /home/runner/TornadoChatRoom/app.py:378]
2024-12-12 06:32:46,776 INFO: Socket connection authenticated for user: Hollow [in /home/runner/TornadoChatRoom/app.py:384]
2024-12-12 06:32:46,777 INFO: Authenticated user connecting: Hollow [in /home/runner/TornadoChatRoom/app.py:386]
2024-12-12 06:32:47,496 INFO: Client connected successfully: Hollow [in /home/runner/TornadoChatRoom/app.py:413]
2024-12-12 06:32:49,173 INFO: Socket connection attempt from zAGR2qkuD8krpAJDAAAX [in /home/runner/TornadoChatRoom/app.py:378]
2024-12-12 06:32:49,435 INFO: Socket connection authenticated for user: Hollow [in /home/runner/TornadoChatRoom/app.py:384]
2024-12-12 06:32:49,435 INFO: Authenticated user connecting: Hollow [in /home/runner/TornadoChatRoom/app.py:386]
2024-12-12 06:32:50,152 INFO: Client connected successfully: Hollow [in /home/runner/TornadoChatRoom/app.py:413]
2024-12-12 06:52:10,415 INFO: User Hollow joined channel general [in /home/runner/TornadoChatRoom/app.py:747]
2024-12-12 06:52:10,484 INFO: Found 50 messages for channel 1 [in /home/runner/TornadoChatRoom/app.py:751]
2024-12-12 06:52:11,068 INFO: System message sent for user Hollow joining channel general [in /home/runner/TornadoChatRoom/app.py:771]
2024-12-12 06:52:13,644 ERROR: No channel_id provided [in /home/runner/TornadoChatRoom/app.py:737]
2024-12-12 06:52:17,185 ERROR: No channel_id provided [in /home/runner/TornadoChatRoom/app.py:737]
2024-12-12 06:52:17,897 ERROR: No channel_id provided [in /home/runner/TornadoChatRoom/app.py:737]
2024-12-12 06:52:22,165 ERROR: No channel_id provided [in /home/runner/TornadoChatRoom/app.py:737]
